name: Install and compile graphql-subscription-example
on: push

jobs:
  gqlsubsexample:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js 18
        uses: actions/setup-node@v5
        with:
          node-version: 18.x
      - name: Install dependencies
        run: npm ci
      - name: Run linting
        run: npm run lint
      - name: Run build
        run: npm run build
